service: node-agent-packager

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: "${opt:stage, 'development'}"
  timeout: 240
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: AgentsBucket
            - '/*'

  environment:
    PKG_CACHE_PATH: /tmp
    PKG_TARGET_PATH: /tmp
    BUCKET_NAME: ${self:custom.bucket}
    REGION: ${self:provider.region}

custom:
  bucket: "${self:service}-${self:provider.stage}"

functions:
  package:
    handler: handler.package
    # events:
    #   - http:
    #       path: package
    #       method: get
    #       cors: true

resources:
  - ${file(resources/bucket.yml)}
  - Outputs:
      AgentsBucketName:
        Value:
          Ref: AgentsBucket

    # ServiceEndpoint:
    #   Description: API Gateway endpoint
    #   Value:
    #     Fn::Join:
    #       - ""
    #       - - "https://"
    #         - "Ref": "ApiGatewayRestApi"
    #         - ".execute-api.eu-west-1.amazonaws.com/dev"


plugins:
  - serverless-export-env

# plugins:
#   - serverless-stack-output
